### ISSUE TITLE
Cancel button in the Edit requirement page

### ISSUE THREAD

**Issue by cechticky** [pnp-software/cordetfw_editor#49]
It's not obvious how to return back from the edit requirement page. There is the "Submit" button, which updates the requirement record in the db, but if a user wants to leave the requirement unchanged, then it's not obvious how to do it. Probably, a "Cancel" button would solve it.

**Comment by pasetti** [comment]
One can return by simply pressing the "return" button on the browser....

I agree it would be nice to have a "back" button in the form but I could not find a satisfactory way of doing this. Here are the three options I tried:

**Add "Back" Button in Form**
In method `SpecItemForm.__init__`, I added:

`self.helper.add_input(Submit('back', Back'))`

This results in a nice looking "Back" button being added next to the "Submit" button. This is exactly what we want from a graphical point of view. However, when I press the "Back" button, the field validator asks me to provide values for mandatory fields (e.g. `Name` or `Domain`). And hence I am stuck

**Add "Back" Button in Template**
In the `basic_form.html` template, I add a button like this:

```
<form method="post">{% csrf_token %}
    <input class="btn btn-success" type="back" value="Back" />
</form>
```

This gives me a button which is not aligned with the "Submit" button (and I do not believe there is a way to make it aligned). However, from a functional point of view, this is what I want because, when i press the "Back" button, I am taken back to the view method and I can process it as I wish.

**Add "Back" Hyperlink in Template**
In the `basic_form.html` template, I add a hyperlink like this:

```
<a href="{% url 'my_target_url' }" class="btn btn-secondary">Back</a>
```
This looks like a button but there is no way to align it with the "Submit" button. From a functional point of view, this can be made to work as we wish.

**Conclusion**
I do not see any way to solve this problem in a way which is acceptable both from a functional and from an aesthetic point of view.

**Comment by PStump** [comment]
To create a cancel button, you can add following snippet into `SpecItemForm.__init__`
```python
self.helper.add_input(Button('cancel', 'Cancel', onclick="location.href='http://localhost:8000/editor';"))
```
(exchange `http://localhost:8000/editor` with the appropriate function/location.

**Comment by pasetti** [comment]
Thanks, Pascal. This is a very good solution. I have tried it and it works but I have two questions:

(1) The 'Cancel' button is added with default colour and decoration. How do I make look like the 'Submit' button (maybe with a different colour)?

(2) Ideally, I would like to define the location to which the user is re-directed if he presses 'Cancel' dynamically. In other words, I would like something like this:

```
target_location = ... 
self.helper.add_input(Button('cancel', 'Cancel', onclick="location.href='target_location';"))
```
I have tried this but it does not work (at least not as shown above). Do you know if it is possible to make it work somehow? If not, I will keep the re-direction to the home page of the editor. it is better than nothing.

**Comment by PStump** [comment]
1. It is possible to add any class in the `css_class` parameter [Bootstrap - Buttons](https://getbootstrap.com/docs/4.6/components/buttons/), e.g.:
```python
self.helper.add_input(Button('cancel', 'Cancel', onclick="location.href='http://localhost:8000/editor';", css_class='btn-outline-secondary'))
```
2. `onclick` is a normal string :wink: 
```python
target_location = 'http://localhost:8000/editor'
self.helper.add_input(Button('cancel', 'Cancel', onclick="location.href='"+target_location+"';", css_class='btn-outline-secondary'))
```

**Comment by pasetti** [comment]
Thanks to Pascal's tips, I have completed the change: the forms to add or edit a spec item now have a "cancel" button
